skynet.start(function ()
	local testd = skynet.newservice("script/service/testd")
	print("send noret",skynet.send(testd,"lua","noret",1,2,3))
	--print("call noret",skynet.call(testd,"lua","noret",1,2,3))
	print("send ret",skynet.send(testd,"lua","ret",1,2,3))
	print("call ret",skynet.call(testd,"lua","ret",1,2,3))
	--print("send assert",skynet.send(testd,"lua","assert",1,2,3))
	--print("call assert",skynet.call(testd,"lua","assert",1,2,3))
	print("send error",skynet.send(testd,"lua","error",1,2,3))
	print("call error",skynet.call(testd,"lua","error",1,2,3))
end)
