require "script.constant.system"
require "script.constant.task"
require "script.constant.team"
require "script.constant.war"
require "script.constant.scene"
require "script.constant.resource"
require "script.constant.other"
