-- team
NO_TEAM						= 0
TEAM_CAPTAIN				= 1
TEAM_STATE_FOLLOW			= 2
TEAM_STATE_LEAVE			= 3
TEAM_STATE_OFFLINE			= 4
TEAM_STATE_ALL				= 5

-- messagebox
MB_RECALLMEMBER				= 1
MB_INVITE_JOINTEAM			= 2
MB_APPLY_BECOME_CAPTAIN		= 3

